spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#  com.imooc.LoggerTest: debug

wechat:
  mpAppId: wx89940ca2633f607a
  mpAppSecret: 31bc7d974554f7f11fc630de4e023119
  mchId: 148xxxxxxxx
  mchKey: xxxxxxxxx
  keyPath: E:/var/weixin_cert/h5.p12
  notifyUrl: http://look.natapp1.cc/sell/pay/notify
